[versions]
dockcrossPlugin = "0.4.2"
jniAccessGenerator = "1.2.2"
mavenCentralPublish = "0.9.0"
jdtAnnotations = "2.4.0"
slf4j = "2.0.17"
logback = "1.5.20"
junitJupiter = "6.0.0"

[libraries]
jniAccessGenerator = { module = "tel.schich:jni-access-generator", version.ref = "jniAccessGenerator" }
jdtAnnotations = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version.ref = "jdtAnnotations" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }

[plugins]
dockcross = { id = "tel.schich.dockcross", version.ref = "dockcrossPlugin" }
mavenCentralPublish = { id = "io.github.zenhelix.maven-central-publish", version.ref = "mavenCentralPublish" }
